name: college-resource-hub
services:
  - name: api
    type: web
    build:
      type: docker
    ports:
      - port: 8080
        protocol: http
    env:
      - key: PORT
        value: "8080"
    health_checks:
      - path: /api/resources/hello
        protocol: http
        port: 8080
